[workspace]
resolver = "2"
members = [
    "commands",
    # "./domain",
    # "./ca_driver",
    # "./signer_verifier",
    # "./infrastructure/sled_repository",
    "common",
    # "ubiquitimes/poise",
    "ubiquitimes/shuttle",
    # "sb/commands",
    # "sb/slcommands",
    # "sb/crypt",
    # "sb/sled",
]

[profile.dev]
debug = 0

# cargo new ubiquitimes/serenity --name ubiquitimes-serenity --vcs none
# cargo shuttle init api/shuttle  --name api-shuttle
# cargo new sb/slcommands --name sb-slcommands --vcs none