[workspace]
members = [
    "commands",
    "ubiquitimes/serenity",
    "sb/commands",
]

# cargo new ubiquitimes/serenity --name ubiquitimes-serenity --vcs none
# cargo shuttle init api/shuttle  --name api-shuttle
