[workspace]
members = [
    "commands",
    "common",
    "ubiquitimes/poise",
    # "ubiquitimes/shuttle",
    # "sb/commands",
    # "sb/slcommands",
    # "sb/crypt",
]

# cargo new ubiquitimes/serenity --name ubiquitimes-serenity --vcs none
# cargo shuttle init api/shuttle  --name api-shuttle
# cargo new sb/slcommands --name sb-slcommands --vcs none