[workspace]
members = [
    "commands",
    "common", "domain", "infrastructure/sled_repository", 
    # "ubiquitimes/poise",
    "ubiquitimes/shuttle",
    # "sb/commands",
    # "sb/slcommands",
    # "sb/crypt",
    # "sb/sled",
]
resolver = "2"

# cargo new ubiquitimes/serenity --name ubiquitimes-serenity --vcs none
# cargo shuttle init api/shuttle  --name api-shuttle
# cargo new sb/slcommands --name sb-slcommands --vcs none