[package]
name = "crypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rsa = {version = "*", features = ["sha2"]}
spki = "*"
base64ct = "*"
